odom:
  marg: false
  num_kfs: 4
  num_levels: 4
  vis_min_depth: 0.5
  reinit: true
  init_depth: false
  init_stereo: true
  init_align: true
select:
  min_grad: 4
stereo:
  min_depth: 0.5
align:
  affine: false
  stereo: false
adjust:
  affine: false
  stereo: true
